openapi: 3.0.0

info:
  title: Population Management System
  description: This API allows users to manage Population data for locations
  version: 1.0.0

servers:
  - url: '{protocol}://127.0.0.1:{port}/v1'
    description: Development server (uses test data)
    variables:
      port:
        enum:
          - "3000"
        default: "3000"
      protocol:
        enum:
          - http
          - https
        default: http

consumes:
  - application/json

content:
  - application/json

paths:
  /locations:
    get:
      summary: List all locations
      description: Allow users to get a list of all created locations
      tags:
        - Locations

      responses:
        "200":
          description: Get locations succesfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/responses/BaseResponseData"
                  - type: object
                    properties:
                      data:
                        locations:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                              name:
                                type: string
                              totalMaleCount:
                                type: number
                              totalFemaleCount:
                                type: number
              examples:
                SuccessGetLocations:
                  value:
                    status: success
                    message: Created location successfully
                    data:
                      locations:
                        - name: Karura
                          _id: fabcd1234976fcdebdef
                          totalMaleCount: 20000
                          totalFemaleCount: 21000
                        - name: Karura Child
                          _id: fabcd1234976fcdebdef
                          totalMaleCount: 20000
                          totalFemaleCount: 21000
                          parentLocationId: fabcd1234976fcdebdef

    post:
      summary: Creates new location containing data about the total number of people by gender. Locations can be nested within each other
      description: Allows users to create a new location 
      tags:
        - Locations

      requestBody:
        description: Data containing information about the location to be created. **NB: See child location example payload from the examples picklist below. Substitute the `parentLocationId` with the _id generated when the parent location was created**
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
            examples:
              CreateKarura:
                value:
                  name: Karura Area
                  maleCount: 20000
                  femaleCount: 21000
              CreateKaruraChildLocation:
                value:
                  name: Karura Child
                  maleCount: 2000
                  femaleCount: 2000
                  parentLocationId: fabcd1234976fcdebdef

      responses:
        "201":
          description: On successful creation of a new location
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/responses/BaseResponseData"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          createdLocation:
                            $ref: "#/components/responses/Location"
              examples:
                CreateKaruraChildSuccess:
                  value:
                    status: success
                    message: Created location successfully
                    data:
                      createdLocation:
                        _id: 5d2ad1bc646edc0d4a93e214
                        name: Karura Child
                        maleCount: 2000
                        femaleCount: 2000
                        parentLocationId: 5abcdef342393948abcd
                      parentLocation:
                        _id: 5abcdef342393948abcd
                        name: Karura Area
                        maleCount: 18000
                        femaleCount: 19000
                        parentLocationId: 5abcdef342393948abcd

        "400":
          description: Bad request - arises when the request body is invalid. This may also arise when there are not enough people in a location to create a sub-location witht the specified demographic data 
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/responses/BaseFailureResponseData"
                  - type: object
                    properties:
                      error:
                        path:
                          type: string
              examples:
                MissingFemaleCount:
                  value:
                    status: fail
                    message: Missing or invalid value in request body
                    errorCode: INVALIDBODY
                    error:
                      path: femaleCount
                NotEnoughFemalesToCreateSublocation:
                  value:
                    status: fail
                    message: Not enough females in parent location to assign new location
                    errorCode: INADEQUATEHEADCOUNT
                    parentLocation:
                      _id: 5abcdef342393948abcd
                      name: Karura Area
                      maleCount: 18000
                      femaleCount: 19000
                      parentLocationId: 5abcdef342393948abcd



        "404":
          description: Missing resource - when the request can not be served due to a missing resource 
          content:
            application/json:
              schema:
                $ref: "#/components/responses/BaseFailureResponseData"
              examples: 
                MissingParentLocation:
                  value:
                    status: fail
                    message: Parent location not found
                    errorCode: UNKNOWNPARENTLOCATION



# schemas for requests and responses
components:
  schemas:
    Location:
      type: object
      properties:
        name:
          type: string
          required: true
        maleCount:
          type: number
          required: true
        femaleCount:
          type: number
          required: true
        parentLocationId:
          type: string
          required: false

  responses:
    BaseResponseData:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

    BaseFailureResponseData:
      allOf:
        - $ref: "#/components/responses/BaseResponseData"
        - type: object
          properties:
            errorCode:
              type: string


    Location:
      allOf:
        - $ref: "#/components/schemas/Location"
        - type: object
          properties:
            _id: 
              type: string
      

